# Generated by Django 3.0.5 on 2020-06-03 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('line', models.CharField(blank=True, default='', max_length=100, verbose_name='Линейка')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('poster', models.TextField(verbose_name='Глав. изображение')),
                ('slug', models.SlugField(default='', max_length=200, verbose_name='slug')),
                ('tagline', models.CharField(default='', max_length=200, verbose_name='Слоган')),
                ('tagline_ru', models.CharField(default='', max_length=200, null=True, verbose_name='Слоган')),
                ('tagline_en', models.CharField(default='', max_length=200, null=True, verbose_name='Слоган')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('description_ru', models.TextField(default='', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(default='', null=True, verbose_name='Описание')),
                ('about_design', models.TextField(blank=True, default='', verbose_name='Про дизайн')),
                ('about_design_ru', models.TextField(blank=True, default='', null=True, verbose_name='Про дизайн')),
                ('about_design_en', models.TextField(blank=True, default='', null=True, verbose_name='Про дизайн')),
                ('about_comfort', models.TextField(blank=True, default='', verbose_name='Про комфорт')),
                ('about_comfort_ru', models.TextField(blank=True, default='', null=True, verbose_name='Про комфорт')),
                ('about_comfort_en', models.TextField(blank=True, default='', null=True, verbose_name='Про комфорт')),
                ('about_controllability', models.TextField(blank=True, default='', verbose_name='Про управляемость')),
                ('about_controllability_ru', models.TextField(blank=True, default='', null=True, verbose_name='Про управляемость')),
                ('about_controllability_en', models.TextField(blank=True, default='', null=True, verbose_name='Про управляемость')),
                ('feature_number1', models.CharField(default='', max_length=150, verbose_name='Число первой особенности')),
                ('feature_text1', models.CharField(default='', max_length=150, verbose_name='Текст первой особенности')),
                ('feature_text1_ru', models.CharField(default='', max_length=150, null=True, verbose_name='Текст первой особенности')),
                ('feature_text1_en', models.CharField(default='', max_length=150, null=True, verbose_name='Текст первой особенности')),
                ('feature_number2', models.CharField(default='', max_length=150, verbose_name='Число второй особенности')),
                ('feature_text2', models.CharField(default='', max_length=150, verbose_name='Текст второй особенности')),
                ('feature_text2_ru', models.CharField(default='', max_length=150, null=True, verbose_name='Текст второй особенности')),
                ('feature_text2_en', models.CharField(default='', max_length=150, null=True, verbose_name='Текст второй особенности')),
                ('feature_number3', models.CharField(default='', max_length=150, verbose_name='Число третей особенности')),
                ('feature_text3', models.CharField(default='', max_length=150, verbose_name='Текст третей особенности')),
                ('feature_text3_ru', models.CharField(default='', max_length=150, null=True, verbose_name='Текст третей особенности')),
                ('feature_text3_en', models.CharField(default='', max_length=150, null=True, verbose_name='Текст третей особенности')),
                ('power', models.CharField(default='', max_length=100, verbose_name='Мощность')),
                ('power_ru', models.CharField(default='', max_length=100, null=True, verbose_name='Мощность')),
                ('power_en', models.CharField(default='', max_length=100, null=True, verbose_name='Мощность')),
                ('number_of_packages', models.CharField(default='', max_length=100, verbose_name='Количество мест')),
                ('acceleration', models.CharField(default='', max_length=100, verbose_name='Разгон')),
                ('acceleration_ru', models.CharField(default='', max_length=100, null=True, verbose_name='Разгон')),
                ('acceleration_en', models.CharField(default='', max_length=100, null=True, verbose_name='Разгон')),
                ('max_speed', models.CharField(default='', max_length=100, verbose_name='Максимальная скорость')),
                ('max_speed_ru', models.CharField(default='', max_length=100, null=True, verbose_name='Максимальная скорость')),
                ('max_speed_en', models.CharField(default='', max_length=100, null=True, verbose_name='Максимальная скорость')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageSlider1', models.TextField(default='', verbose_name='Картинка для слайдера 1')),
                ('imageSlider2', models.TextField(default='', verbose_name='Картинка для слайдера 2')),
                ('imageSlider3', models.TextField(default='', verbose_name='Картинка для слайдера 3')),
                ('imageAbout1', models.TextField(default='', verbose_name='Дизайн')),
                ('imageAbout2', models.TextField(default='', verbose_name='Комфорт')),
                ('imageAbout3', models.TextField(default='', verbose_name='Управляемость')),
                ('imageGallery1', models.TextField(default='', verbose_name='Картинка для галереи 1')),
                ('imageGallery2', models.TextField(default='', verbose_name='Картинка для галереи 2')),
                ('imageGallery3', models.TextField(default='', verbose_name='Картинка для галереи 3')),
                ('imageGallery4', models.TextField(default='', verbose_name='Картинка для галереи 4')),
                ('imageGallery5', models.TextField(default='', verbose_name='Картинка для галереи 5')),
                ('imageGallery6', models.TextField(default='', verbose_name='Картинка для галереи 6')),
                ('car', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CarShowroom.Car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Привод',
                'verbose_name_plural': 'Приводы',
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Двигатель',
                'verbose_name_plural': 'Двигатели',
            },
        ),
        migrations.CreateModel(
            name='Modeltype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип модели',
                'verbose_name_plural': 'Типы моделей',
            },
        ),
        migrations.CreateModel(
            name='PurchaseCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=200, verbose_name='Модель авто')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 6, 3, 15, 8, 5, 408591), verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Запрос к дилеру',
                'verbose_name_plural': 'Запросы к дилеру',
            },
        ),
        migrations.CreateModel(
            name='ServiceCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=200, verbose_name='Модель авто')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('time', models.CharField(max_length=50, verbose_name='Время')),
                ('date', models.DateTimeField(verbose_name='Дата записи')),
                ('date_send', models.DateTimeField(default=datetime.datetime(2020, 6, 3, 15, 8, 5, 409591), verbose_name='Дата отправки заявки')),
            ],
            options={
                'verbose_name': 'Заявка на сервис',
                'verbose_name_plural': 'Заявки на сервис',
            },
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('car_model', models.CharField(max_length=100, verbose_name='Модель авто')),
                ('time', models.CharField(max_length=50, verbose_name='Время')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('send_data', models.DateTimeField(default=None, verbose_name='Дата отправки заявки')),
            ],
            options={
                'verbose_name': 'Запись на тест драйв',
                'verbose_name_plural': 'Записи на тест драйв',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Коробка передач',
                'verbose_name_plural': 'Коробки передач',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Рейтинг отзыва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.TextField(verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='car',
            name='drive',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CarShowroom.Drive', verbose_name='Привод'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CarShowroom.Engine', verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CarShowroom.Modeltype', verbose_name='Тип модели'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_type_en',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='CarShowroom.Modeltype', verbose_name='Тип модели'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_type_ru',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='CarShowroom.Modeltype', verbose_name='Тип модели'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CarShowroom.Transmission', verbose_name='Коробка передач'),
        ),
    ]
