# Generated by Django 3.0.5 on 2020-05-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('line', models.CharField(blank=True, default='', max_length=100, verbose_name='Линейка')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('poster', models.ImageField(upload_to='', verbose_name='Глав. изображение')),
                ('slug', models.SlugField(default='', max_length=200, verbose_name='slug')),
                ('tagline', models.CharField(default='', max_length=200, verbose_name='Слоган')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('about_design', models.TextField(blank=True, default='', verbose_name='Про дизайн')),
                ('about_comfort', models.TextField(blank=True, default='', verbose_name='Про комфорт')),
                ('about_controllability', models.TextField(blank=True, default='', verbose_name='Про управляемость')),
                ('feature_text1', models.CharField(default='', max_length=150, verbose_name='Текст первой особенности')),
                ('feature_text2', models.CharField(default='', max_length=150, verbose_name='Текст второй особенности')),
                ('feature_text3', models.CharField(default='', max_length=150, verbose_name='Текст третей особенности')),
                ('power', models.CharField(default='', max_length=100, verbose_name='Мощность')),
                ('model_type', models.CharField(default='', max_length=100, verbose_name='Тип модели')),
                ('number_of_packages', models.CharField(default='', max_length=100, verbose_name='Количество мест')),
                ('engine', models.CharField(default='', max_length=100, verbose_name='Двигатель')),
                ('drive', models.CharField(default='', max_length=100, verbose_name='Привод')),
                ('transmission', models.CharField(default='', max_length=100, verbose_name='Коробка передач')),
                ('acceleration', models.CharField(default='', max_length=100, verbose_name='Разгон')),
                ('max_speed', models.CharField(default='', max_length=100, verbose_name='Максимальная скорость')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('car_model', models.CharField(max_length=100, verbose_name='Модель авто')),
                ('time', models.CharField(max_length=50, verbose_name='Время')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('send_data', models.DateTimeField(default=None, verbose_name='Дата отправки заявки')),
            ],
            options={
                'verbose_name': 'Запись на тест драйв',
                'verbose_name_plural': 'Записи на тест драйв',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Рейтинг отзыва'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageSlider1', models.ImageField(default='', upload_to='', verbose_name='Картинка для слайдера 1')),
                ('imageSlider2', models.ImageField(default='', upload_to='', verbose_name='Картинка для слайдера 2')),
                ('imageSlider3', models.ImageField(default='', upload_to='', verbose_name='Картинка для слайдера 3')),
                ('imageAbout1', models.ImageField(default='', upload_to='', verbose_name='Дизайн')),
                ('imageAbout2', models.ImageField(default='', upload_to='', verbose_name='Комфорт')),
                ('imageAbout3', models.ImageField(default='', upload_to='', verbose_name='Управляемость')),
                ('imageGallery1', models.ImageField(default='', upload_to='', verbose_name='Картинка для галереи 1')),
                ('imageGallery2', models.ImageField(default='', upload_to='', verbose_name='Картинка для галереи 2')),
                ('imageGallery3', models.ImageField(default='', upload_to='', verbose_name='Картинка для галереи 3')),
                ('imageGallery4', models.ImageField(default='', upload_to='', verbose_name='Картинка для галереи 4')),
                ('imageGallery5', models.ImageField(default='', upload_to='', verbose_name='Картинка для галереи 5')),
                ('imageGallery6', models.ImageField(default='', upload_to='', verbose_name='Картинка для галереи 6')),
                ('car', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CarShowroom.Car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
    ]
