# Generated by Django 3.0.5 on 2020-05-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0002_auto_20200527_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='feature_number1',
            field=models.CharField(default='', max_length=150, verbose_name='Число первой особенности'),
        ),
        migrations.AddField(
            model_name='car',
            name='feature_number2',
            field=models.CharField(default='', max_length=150, verbose_name='Число второй особенности'),
        ),
        migrations.AddField(
            model_name='car',
            name='feature_number3',
            field=models.CharField(default='', max_length=150, verbose_name='Число третей особенности'),
        ),
    ]
