# Generated by Django 3.0.5 on 2020-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0003_auto_20200527_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimages',
            name='imageSlider1',
        ),
        migrations.AddField(
            model_name='carimages',
            name='imageSlider_1',
            field=models.ImageField(default='', upload_to='', verbose_name='Картинка для слайдера 1'),
        ),
    ]
