# Generated by Django 3.0.5 on 2020-05-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0003_auto_20200524_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('car_model', models.CharField(max_length=100, verbose_name='Модель авто')),
                ('time', models.CharField(max_length=50, verbose_name='Время')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Запись на тест драйв',
                'verbose_name_plural': 'Записи на тест драйв',
            },
        ),
    ]
