# Generated by Django 3.0.5 on 2020-06-03 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0003_auto_20200603_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model_type_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model_type_ru',
        ),
        migrations.AddField(
            model_name='modeltype',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='modeltype',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 15, 22, 20, 319489), verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 15, 22, 20, 320489), verbose_name='Дата отправки заявки'),
        ),
    ]
