# Generated by Django 3.0.5 on 2020-06-03 13:12

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0004_auto_20200603_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderInfo', models.CharField(max_length=250, verbose_name='Инфа на слайдере')),
                ('expYears', models.PositiveSmallIntegerField(verbose_name='Лет опыта')),
                ('workers', models.PositiveSmallIntegerField(verbose_name='Кол-во работников')),
                ('dovrelnyClients', models.PositiveIntegerField(verbose_name='Кол-во клиентов')),
                ('electroCarPicture', models.ImageField(upload_to='', verbose_name='Картинка электромобиля')),
                ('electroCarInfo', models.TextField(verbose_name='Описание электромобиля')),
            ],
            options={
                'verbose_name': 'Глав. страница',
                'verbose_name_plural': 'Глав. страницы',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='poster',
            field=models.ImageField(upload_to='', verbose_name='Глав. изображение'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageAbout1',
            field=models.ImageField(upload_to='', verbose_name='Дизайн'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageAbout2',
            field=models.ImageField(upload_to='', verbose_name='Комфорт'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageAbout3',
            field=models.ImageField(upload_to='', verbose_name='Управляемость'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageGallery1',
            field=models.ImageField(upload_to='', verbose_name='Картинка для галереи 1'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageGallery2',
            field=models.ImageField(upload_to='', verbose_name='Картинка для галереи 2'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageGallery3',
            field=models.ImageField(upload_to='', verbose_name='Картинка для галереи 3'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageGallery4',
            field=models.ImageField(upload_to='', verbose_name='Картинка для галереи 4'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageGallery5',
            field=models.ImageField(upload_to='', verbose_name='Картинка для галереи 5'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageGallery6',
            field=models.ImageField(upload_to='', verbose_name='Картинка для галереи 6'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageSlider1',
            field=models.ImageField(upload_to='', verbose_name='Картинка для слайдера 1'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageSlider2',
            field=models.ImageField(upload_to='', verbose_name='Картинка для слайдера 2'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageSlider3',
            field=models.ImageField(upload_to='', verbose_name='Картинка для слайдера 3'),
        ),
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 16, 12, 2, 126039), verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 16, 12, 2, 127039), verbose_name='Дата отправки заявки'),
        ),
    ]
