# Generated by Django 3.0.5 on 2020-05-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0004_auto_20200527_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimages',
            old_name='imageSlider_1',
            new_name='imageSlider1',
        ),
    ]
