# Generated by Django 3.0.5 on 2020-05-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0004_testdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='send_data',
            field=models.DateTimeField(default=None, verbose_name='Дата отправки заявки'),
        ),
    ]
