# Generated by Django 3.0.5 on 2020-06-03 13:28

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0005_auto_20200603_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderInfo', ckeditor_uploader.fields.RichTextUploadingField()),
                ('expYears', models.PositiveSmallIntegerField(verbose_name='Лет опыта')),
                ('workers', models.PositiveSmallIntegerField(verbose_name='Кол-во работников')),
                ('dovrelnyClients', models.PositiveIntegerField(verbose_name='Кол-во клиентов')),
                ('electroCarPicture', models.ImageField(upload_to='', verbose_name='Картинка электромобиля')),
                ('electroCarInfo', ckeditor_uploader.fields.RichTextUploadingField()),
                ('discountSection', ckeditor_uploader.fields.RichTextUploadingField()),
                ('development', models.TextField()),
                ('trust', models.TextField()),
                ('guarantees', models.TextField()),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=50)),
                ('workTime', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Глав. страница',
                'verbose_name_plural': 'Глав. страницы',
            },
        ),
        migrations.DeleteModel(
            name='MainPage',
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description_en',
            field=models.TextField(default='', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description_ru',
            field=models.TextField(default='', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 16, 28, 41, 527201), verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 16, 28, 41, 528201), verbose_name='Дата отправки заявки'),
        ),
    ]
