# Generated by Django 3.0.5 on 2020-05-29 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0005_auto_20200527_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=200, verbose_name='Модель авто')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 5, 29, 10, 31, 23, 591788), verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Запрос к дилеру',
                'verbose_name_plural': 'Запросы к дилеру',
            },
        ),
    ]
