# Generated by Django 3.0.5 on 2020-05-29 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0006_purchasecar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimages',
            name='imageAbout1',
            field=models.TextField(default='', verbose_name='Дизайн'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageAbout2',
            field=models.TextField(default='', verbose_name='Комфорт'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageAbout3',
            field=models.TextField(default='', verbose_name='Управляемость'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageGallery1',
            field=models.TextField(default='', verbose_name='Картинка для галереи 1'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageGallery2',
            field=models.TextField(default='', verbose_name='Картинка для галереи 2'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageGallery3',
            field=models.TextField(default='', verbose_name='Картинка для галереи 3'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageGallery4',
            field=models.TextField(default='', verbose_name='Картинка для галереи 4'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageGallery5',
            field=models.TextField(default='', verbose_name='Картинка для галереи 5'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageGallery6',
            field=models.TextField(default='', verbose_name='Картинка для галереи 6'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageSlider1',
            field=models.TextField(default='', verbose_name='Картинка для слайдера 1'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageSlider2',
            field=models.TextField(default='', verbose_name='Картинка для слайдера 2'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imageSlider3',
            field=models.TextField(default='', verbose_name='Картинка для слайдера 3'),
        ),
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 10, 54, 16, 665659), verbose_name='Дата записи'),
        ),
    ]
