# Generated by Django 3.0.5 on 2020-06-03 13:42

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0006_auto_20200603_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='address_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='address_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='development_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='development_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='discountSection_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='discountSection_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='electroCarInfo_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='electroCarInfo_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='guarantees_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='guarantees_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='trust_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='trust_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='workTime_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='workTime_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 16, 42, 29, 886581), verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 16, 42, 29, 887581), verbose_name='Дата отправки заявки'),
        ),
    ]
