# Generated by Django 3.0.5 on 2020-05-29 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0008_auto_20200529_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.TextField(verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 11, 1, 16, 551183), verbose_name='Дата записи'),
        ),
    ]
