# Generated by Django 3.0.5 on 2020-06-03 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0008_auto_20200603_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 17, 3, 12, 683665), verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 17, 3, 12, 684665), verbose_name='Дата отправки заявки'),
        ),
    ]
