# Generated by Django 3.0.5 on 2020-05-29 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0009_auto_20200529_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=200, verbose_name='Модель авто')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('time', models.CharField(max_length=50, verbose_name='Время')),
                ('date', models.DateTimeField(verbose_name='Дата записи')),
                ('date_send', models.DateTimeField(default=datetime.datetime(2020, 5, 29, 13, 17, 25, 132399), verbose_name='Дата отправки заявки')),
            ],
            options={
                'verbose_name': 'Заявка на сервис',
                'verbose_name_plural': 'Заявки на сервис',
            },
        ),
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 13, 17, 25, 131399), verbose_name='Дата записи'),
        ),
    ]
