# Generated by Django 3.0.5 on 2020-06-05 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0010_auto_20200605_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 23, 33, 9, 891542), verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 23, 33, 9, 892542), verbose_name='Дата отправки заявки'),
        ),
    ]
