# Generated by Django 3.0.5 on 2020-05-29 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0010_auto_20200529_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 15, 33, 29, 750388), verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 15, 33, 29, 751388), verbose_name='Дата отправки заявки'),
        ),
    ]
