# Generated by Django 3.0.5 on 2020-06-06 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0011_auto_20200605_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 8, 42, 17, 326786), verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 8, 42, 17, 328786), verbose_name='Дата отправки заявки'),
        ),
    ]
