# Generated by Django 3.0.5 on 2020-05-29 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0011_auto_20200529_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='about_comfort_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Про комфорт'),
        ),
        migrations.AddField(
            model_name='car',
            name='about_comfort_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Про комфорт'),
        ),
        migrations.AddField(
            model_name='car',
            name='about_controllability_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Про управляемость'),
        ),
        migrations.AddField(
            model_name='car',
            name='about_controllability_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Про управляемость'),
        ),
        migrations.AddField(
            model_name='car',
            name='about_design_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Про дизайн'),
        ),
        migrations.AddField(
            model_name='car',
            name='about_design_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Про дизайн'),
        ),
        migrations.AddField(
            model_name='car',
            name='acceleration_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Разгон'),
        ),
        migrations.AddField(
            model_name='car',
            name='acceleration_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Разгон'),
        ),
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.TextField(default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ru',
            field=models.TextField(default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='car',
            name='drive_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Привод'),
        ),
        migrations.AddField(
            model_name='car',
            name='drive_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Привод'),
        ),
        migrations.AddField(
            model_name='car',
            name='feature_text1_en',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Текст первой особенности'),
        ),
        migrations.AddField(
            model_name='car',
            name='feature_text1_ru',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Текст первой особенности'),
        ),
        migrations.AddField(
            model_name='car',
            name='feature_text2_en',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Текст второй особенности'),
        ),
        migrations.AddField(
            model_name='car',
            name='feature_text2_ru',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Текст второй особенности'),
        ),
        migrations.AddField(
            model_name='car',
            name='feature_text3_en',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Текст третей особенности'),
        ),
        migrations.AddField(
            model_name='car',
            name='feature_text3_ru',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Текст третей особенности'),
        ),
        migrations.AddField(
            model_name='car',
            name='max_speed_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Максимальная скорость'),
        ),
        migrations.AddField(
            model_name='car',
            name='max_speed_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Максимальная скорость'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_type_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Тип модели'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_type_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Тип модели'),
        ),
        migrations.AddField(
            model_name='car',
            name='power_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Мощность'),
        ),
        migrations.AddField(
            model_name='car',
            name='power_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Мощность'),
        ),
        migrations.AddField(
            model_name='car',
            name='tagline_en',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='car',
            name='tagline_ru',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 16, 24, 37, 581858), verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 16, 24, 37, 582858), verbose_name='Дата отправки заявки'),
        ),
    ]
