# Generated by Django 3.0.5 on 2020-06-06 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0012_auto_20200606_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 9, 1, 22, 272273), verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 9, 1, 22, 273273), verbose_name='Дата отправки заявки'),
        ),
    ]
