# Generated by Django 3.0.5 on 2020-05-29 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0012_auto_20200529_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 20, 26, 32, 865085), verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 20, 26, 32, 866085), verbose_name='Дата отправки заявки'),
        ),
    ]
